### ISSUE TITLE
Mobility suggestion

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#10]
For mobility, the baseline of giving each square a small chance to switch places with the neighbour would be a nice way of introducing some mixing into the population.

A suggestion on how to implement quarantine rules: if quarantine is not enabled, symptomatic cases can continue to move. If quarantine cases are enabled, symptomatic cases and the 8 neighbouring squares can no longer move. It would be a fairly realistic way of simulating quarantine.

**Comment by s-andrews** [comment]
For the movement that's fine.  For the quarantine that would mean that the infection would still continue to spread from obviously infected people even with quarantine turned on.  There would be more of an effect if we simply say that obviously ill people can't infect anyone if quarantine is turned on.  We could also stop them moving, but I'd suggest not changing the infection rules.

**Comment by s-andrews** [comment]
This is now done.  It works pretty well in that even if you have a highly vaccinated population a suitably virulent and long-lasting infection can still spread.  Everything can move each day, but because the movement is random you don't tend to get long runs of distance and things tend to stay fairly localised so the view isn't too confusing.
