### ISSUE TITLE
Colour change for immune

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#14]
Could you make immune and vaccinated very close to the same colour? We want to try to emphasize the similarity between the two states. Maybe even just make them the same colour.

**Comment by s-andrews** [comment]
I had them the same colour initially, but it's kind of nice to be able to make the distinction.  One problem I found when they were the same was that having a high propotion of bold colours on the starting screen made it much more difficult to watch the progress of the infections since the new infections stood out much less (hence making them grey).

I'll tidy up the CSS file so that the different colour categories are all nicely abstracted which should make it easy to play around with different options so we can see what works best.

**Comment by s-andrews** [comment]
This is now done and the colours can easily be changed in the future by editing the constants at the top of the main css file.
