### ISSUE TITLE
I changed the default viruses

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#19]
I changed the file with the default virus settings, but I don't think I did it correctly because nothing has changed. My suggested settings:

[
{
"name" : "Influenza",
"virulence" : 0.5,
"incubation" : 2,
"infection" : 4,
"lethality" : 0.05,
"vaccination" : 0.47,
"quarantine" : false
},

{
    "name" : "Measles",
    "virulence" : 0.9,
    "incubation" : 2,
    "infection" : 2,
    "lethality" : 0.03,
    "vaccination" : 0.75,
    "quarantine" : true
},

{
    "name" : "Ebola", 
    "virulence" : 0.05,
    "incubation" : 10,
    "infection" : 5,
    "lethality" : 0.5,
    "vaccination" : 0,
    "quarantine" : false
}
]

**Comment by AdrianListon** [comment]
Actually, better settings, slightly editing Ebola (added quarantine as default, dropped transmission to 2%):

[
{
"name" : "Influenza",
"virulence" : 0.5,
"incubation" : 2,
"infection" : 4,
"lethality" : 0.05,
"vaccination" : 0.47,
"quarantine" : false
},

{
"name" : "Measles",
"virulence" : 0.9,
"incubation" : 2,
"infection" : 2,
"lethality" : 0.03,
"vaccination" : 0.75,
"quarantine" : true
},

{
"name" : "Ebola",
"virulence" : 0.02,
"incubation" : 10,
"infection" : 5,
"lethality" : 0.5,
"vaccination" : 0,
"quarantine" : true
}
]

**Comment by s-andrews** [comment]
The version on the githubpages page (now linked from https://github.com/s-andrews/virusbreak/ should update around a minute after you commit any changes to the virus file since it's directly linked to the repository.   The version on our dev server only updates when I manually go in an pull updates, so this will always be somewhat behind.  I can see the updates on my version and they look to be working OK.

All of your commits get recorded so I can see them without needing to add more issues.  If a change refers to a specific issue then if you put the issue number after a hash symbol in the commit message then it will automatically be tagged onto that issue.
