### ISSUE TITLE
Add introduction blurb

### ISSUE THREAD

**Issue by AdrianListon** [s-andrews/virusbreak#21]
A few sentences at the top of the page would be useful instruction, eg

"What happens when a new virus out-break occurs in the UK? Pick a known virus, or engineer your own, and start an epidemic. What is the effect of vaccination on the costs of the outbreak?"

**Comment by s-andrews** [comment]
I've added a welcome screen when you first load the system.  The content from this is read from a new file I've also added called ```www/intro.html``` so you can edit this to add whatever text you want to appear in this window.  I can sort the formatting out afterwards but you can probably see the basic structure from what's there already.

I'd recommend keeping this fairly brief since this is going to be what people see when they first load the system and before they play the game.

**Comment by s-andrews** [comment]
The CSS for the welcome screen needs some work.  It's not centered properly for some reason. Need to look into it.

**Comment by s-andrews** [comment]
CSS is fixed and there is content in the intro help.
